---
title: "Argentina's historical GDP trends"
author: "Alejandra Gerosa"
date: "9/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(cowplot)

caption <- "En base a datos de Maddison Project Database. Datos y código disponibles en github.com/alegerosa/maddison-project-data"
  
  
```

## Load the data



```{r data}
data <- read_xlsx("data/mpd2018.xlsx", sheet = 2)



```

## Add ranking

```{r ranking}
gdp_with_rankings <- data %>%
  group_by(year) %>%
  mutate(rank = row_number(desc(cgdppc)),
         perc_rank = percent_rank(cgdppc),
         percentile = perc_rank * 100,
         rank_better_ties = rank(desc(cgdppc), ties.method = "min", na.last = "keep"))
```

## Reproduce original plot

```{r plot_orig}

p <- gdp_with_rankings %>%
  filter(countrycode %in% c("ARG", "AUS"),
         year >= 1850) %>% 
  ggplot(aes(x = year, rank, color = country)) +
  geom_line() +
  scale_y_reverse() +
  geom_text(data = filter(gdp_with_rankings, year == "2016" & countrycode %in% c("ARG", "AUS")), aes(label = country, colour = country, x = Inf, y = rank), hjust = 1) +
  guides(color = FALSE) +
  labs(x = NULL,
       y = "Ranking",
      title = "El gráfico original",
      subtitle = "Compara puestos absolutos (sin importar cuántos países)",
      caption = " ") +
  geom_smooth(se = FALSE)
p

```


```{r count_countries}
counts <- gdp_with_rankings %>%
  group_by(year) %>% 
  summarise(count = sum(!is.na(rgdpnapc))) %>% 
  filter(year >= 1850) %>%
  ggplot(aes(year, count))

counts + geom_line()

```

```{r perc_rank_plot}
q <- gdp_with_rankings %>%
  filter(countrycode %in% c("ARG", "AUS"),
         year >= 1850) %>% 
  ggplot(aes(year, percentile, color = country)) +
  geom_line() +
  scale_y_continuous(labels = scales::ordinal) +
  coord_cartesian(ylim=c(0,100)) +
  geom_text(data = filter(gdp_with_rankings, year == "2016" & countrycode %in% c("ARG", "AUS")), aes(label = country, colour = country, x = Inf, y = percentile), hjust = 1) +
  guides(color = FALSE) +
  labs(x = NULL,
       y = "Percentil",
      title = "Un gráfico algo más razonable",
      subtitle = "Compara puestos relativos (percentiles)",
      caption = caption) +
  geom_smooth(se = FALSE)

q


```

```{r together}
graficos <- plot_grid(p, q)

ggsave("graficos.jpg", graficos, width = 12, height = 4 )
```


```{r other_plots}
comparisons <- c("ARG", "AUS", "USA", "VEN", "MEX", "CHL", "PER", "BRA", "IRL", "ITA", "ESP", "PRY")

gdp_plot <- gdp_with_rankings %>%
  filter(year >= 1850, countrycode %in% comparisons) %>% 
  ggplot(aes(year, cgdppc, color = country))

gdp_plot + geom_line() +
  facet_wrap(~country) + guides(color = FALSE) +
  geom_vline(xintercept = 1950, color = "pink") +
  geom_vline(xintercept = 1975, color = "pink")




  

```

```{r plots_rgd}

gdp_with_rgd_rankings <- data %>%
  group_by(year) %>%
  mutate(rank = row_number(desc(rgdpnapc)),
         perc_rank = percent_rank(rgdpnapc),
         percentile = perc_rank * 100,
         rank_better_ties = rank(desc(rgdpnapc), ties.method = "min", na.last = "keep"))

rgd <- gdp_with_rgd_rankings %>%
  filter(countrycode %in% c("ARG", "AUS"),
         year >= 1850) %>% 
  ggplot(aes(x = year, rank, color = country)) 

rgd + geom_line() +
  scale_y_reverse() +
  geom_smooth(se = FALSE)

perc_rgd <- gdp_with_rgd_rankings %>%
  filter(countrycode %in% c("ARG", "AUS"),
         year >= 1850) %>% 
  ggplot(aes(year, percentile, color = country))

perc_rgd + geom_line() +
  scale_y_continuous(labels = scales::ordinal) +
  coord_cartesian(ylim=c(0,100)) +
  geom_smooth(se = FALSE)



```